#!/usr/bin/env bash
# This script calculates the product of the two largest prime factors for a given number

calculate_factors() {
    # Check if the correct number of arguments is provided
    if [ $# -ne 1 ]; then
        echo "Usage: calculate_factors <number>"
        exit 1
    fi

    # Use the 'factor' command to find the prime factors, then process the output
    factors=$(factor "$1" | awk '{$1=""; print $0}' | sed 's/ //g')
    factors_array=($factors)

    # Check if the number has only one prime factor
    if [ ${#factors_array[@]} -eq 1 ]; then
        echo "$1=1*$1"
    else
        max_factor=${factors_array[-1]}
        second_max_factor=${factors_array[-2]}

        # If there are more than two factors, find the two largest prime factors
        if [ ${#factors_array[@]} -gt 2 ]; then
            for ((i=${#factors_array[@]}-3; i>=0; i--)); do
                if [ $(echo "${factors_array[$i]}*$second_max_factor" | bc) -gt $(echo "$max_factor*${
                factors_array[$i+1]}" | bc) ]; then
                    break
                fi

                second_max_factor=${factors_array[$i]}
            done
        fi

        echo "$1=$max_factor*$second_max_factor"
    fi
}

if [ $# -ne 1 ]; then
    echo 'Usage: factor_calculator <file>'
    exit 1
else
    # Read numbers from a file and calculate their two largest prime factors
    while read -r number; do
        calculate_factors "$number"
    done < "$1"
fi

