#!/usr/bin/env python3
import sys
import gmpy2

def factorize_rsa_number(n):
    p = gmpy2.mpz(2)
    q = gmpy2.mpz(1)
    
    while q == 1:
        p = gmpy2.next_prime(p)
        q, r = divmod(n, p)
    
    return p, q

if __name__ == "__main__":
    if len(sys.argv) != 2:
        print("Usage: python3 factorize_rsa.py <number>")
        sys.exit(1)

    n = gmpy2.mpz(sys.argv[1])
    p, q = factorize_rsa_number(n)
    
    print(f"p = {p}")
    print(f"q = {q}")

